# Generated by Django 2.1.5 on 2019-01-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190119_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_hired', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
