# Generated by Django 2.1.5 on 2019-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='courses.Faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ManyToManyField(to='courses.Department'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='owner',
            field=models.ManyToManyField(to='courses.Faculty'),
        ),
    ]
